### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/TES_3Soils_2021#2]
### 1. Characterization
- [x] summary table 
- [x] pore size distribution  
~~redo water retention curves~~

### 2. WSOC/NPOC
- [x] soils: table
- [x] pore water: 3 figures?
- [x] **CHECK SOILS WSOC MG/G CALCULATION**

###  3. FTICR

- [x] Van-Krevelens
- [x] relative abundance of groups
- [x] new/lost molecules for each treatment
- [x] unique molecules for each treatment?
- [x] abundance of aromatic molecules (**AI_mod > 0.5**)
- [x] Kendrick mass?

**Comment by kaizadp** [comment]
- [ ]  submit raw, demultiplexed sequence data to online database NCBI. Include in the Data availability section. Probably can be added after we submit for review.

**Comment by kaizadp** [comment]
store data on ESS-DIVE:
- both, raw and processed data
- link to GitHub repo
- add a Zenodo DOI for GitHub repo. release version. update releases as needed.
- one Readme at the root. describe the folder structure and the data

**Comment by kaizadp** [comment]
ALL DONE!

**Comment by bpbond** [comment]
@kaizadp !!! 👏 👏 👏 👏
